server:
  servlet:
    context-path: /
  port: 4041
  compression:
    enabled: true
    mime-types: application/javascript,text/css,text/plain,application/xml,text/html,text/xml
  tomcat:
    uri-encoding: utf-8
    max-http-form-post-size: 20MB
    max-swallow-size: 20MB
    threads:
      max: 4000

spring:
  profiles:
    active: dev
  #大小限制
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  #设置抛出报错
  mvc:
    throw-exception-if-no-handler-found: true
  #设置static可访问，其他在config中配置
  #message
  messages:
    basename: i18n/messages
  #设置json解码
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #aop切面
  aop:
    proxy-target-class: true
    auto: true
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  # 实体类扫描路径
  type-aliases-package: com.thinker.**.entity
  # xml 扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
    cache-enabled: true
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false